# Generated by Django 5.1.5 on 2025-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='type',
        ),
        migrations.AddField(
            model_name='trip',
            name='attractions',
            field=models.ManyToManyField(related_name='trips', to='trips.attraction'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
